layout:
  name: custom  # Use 'custom' if chocofi isn’t recognized, or try removing this field
  rows: 4       # Number of rows in your keymap
  columns: 10   # Number of columns in your keymap

layers:
  - DEFAULT
  - QWERTY
  - NUM
  - NAV
  - FUN

keymap:
  DEFAULT:
    - [ Q, W, F, P, B, J, L, U, Y, EQUAL ]
    - [ HRM(LEFT_WIN A), HRM(LEFT_ALT R), HRM(LCTRL S), HRM(LEFT_SHIFT T), G, M, HRM(LEFT_SHIFT N), HRM(LCTRL E), HRM(LEFT_ALT I), HRM(LEFT_WIN O) ]
    - [ Z, X, C, D, V, K, H, COMMA_SEMI, DOT_COLON, SLASH ]
    - [ CAPS_WORD, BACKSPACE, LAYER_TAP(NUM, TAB), LAYER_TAP(NAV, ENTER), LAYER_TAP(FUN, SPACE), SUPER_BSPC ]

  NUM:
    - [ NONE, NONE, ENTER, BACKSPACE, NONE, MINUS, N7, N8, N9, EQUAL ]
    - [ LEFT_WIN, LEFT_ALT, LCTRL, LEFT_SHIFT, NONE, PLUS, N4, N5, N6, ASTERISK ]
    - [ AMPS_MORPH, NONE, NONE, NONE, NONE, DELETE, N1, NUM_2_COMMA, NUM_3_PERIOD, SLASH ]
    - [ TRANS, TRANS, TRANS, ENTER, SPACE, NUMBER_0 ]

  NAV:
    - [ TRANS, TRANS, ENTER, TRANS, TRANS, TRANS, HOME, UP_ARROW, END, NONE ]
    - [ LEFT_WIN, LEFT_ALT, LCTRL, LEFT_SHIFT, TAB, NONE, LEFT, DOWN, RIGHT, PAGE_UP ]
    - [ TRANS, NONE, LC(LS(TAB)), LC(TAB), TRANS, DELETE, K_COPY, K_CUT, K_PASTE, PAGE_DOWN ]
    - [ TRANS, BACKSPACE, TAB, TRANS, TRANS, TRANS ]

  FUN:
    - [ BACKSLASH, PERCENT, LEFT_BRACE, RIGHT_BRACE, AMPS, TRANS, LC(Z), LS(LC(Z)), GRAVE, SINGLE_QUOTE ]
    - [ AT, ASTRK, LEFT_PARENTHESIS, HRM(LEFT_SHIFT RIGHT_PARENTHESIS), EXCL, DEL, LSHFT, LCTRL, LALT, LEFT_WIN ]
    - [ CARET, HASH, LBKT, RBKT, DOLLAR, TRANS, TRANS, TRANS, TRANS, SEMI ]
    - [ TRANS, BACKSPACE, TAB, TRANS, TRANS, TRANS ]
